/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Push Notifications
self.addEventListener('push', (event) => {
  if (event.data) {
    try {
      const data = event.data.json();
      console.log('Push received:', data);
      
      const title = data.title || 'Skibidi Film';
      const iconUrl = data.icon 
        ? new URL(data.icon, self.location.origin).href 
        : new URL('/pwa-192x192.png', self.location.origin).href;
      
      const options = {
        body: data.body || 'Nuova notifica disponibile!',
        icon: iconUrl,
        badge: new URL('/pwa-192x192.png', self.location.origin).href,
        data: {
          url: data.url || '/'
        }
      };

      if (data.tag) options.tag = data.tag;
      if (data.image) options.image = data.image;
      if (Array.isArray(data.actions) && data.actions.length > 0) {
        options.actions = data.actions;
      }
      if (Array.isArray(data.vibrate) && data.vibrate.length > 0) {
        options.vibrate = data.vibrate;
      }

      event.waitUntil(self.registration.showNotification(title, options));
    } catch (e) {
      console.error('Error parsing push data:', e);
      // Fallback for non-JSON payload
      const fallbackIcon = new URL('/pwa-192x192.png', self.location.origin).href;
      event.waitUntil(
        self.registration.showNotification('Skibidi Film', {
          body: event.data ? event.data.text() : 'Nuova notifica disponibile!',
          icon: fallbackIcon,
          data: { url: '/' }
        })
      );
    }
  }
});

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const targetUrl = event.notification.data.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
